const fs = require("fs");
const p = require("path");
const target = p.join("C:", "Users", "ahmet", "Desktop", ".github", "adaptive-math-learning", "backend", "services", "enhanced_parent_teacher_service.py");
const Q = '"';
const Q3 = '"""';
const SQ = "'";

let py = "";

// Helper to add lines
function A(line) { py += line + "\n"; }
function B() { py += "\n"; }

// =========================================================================
// HomeworkService
// =========================================================================
B();
B();
A("# ---------------------------------------------------------------------------");
A("# HomeworkService - Odev Yonetimi");
A("# ---------------------------------------------------------------------------");
B();
A("class HomeworkService:");
A("    " + Q3);
A("    Odev olusturma, teslim alma ve otomatik degerlendirme servisi.");
A("    Ogretmenler odev olusturur, ogrenciler teslim eder,");
A("    sistem otomatik olarak degerlendirir.");
A("    " + Q3);
B();
A("    def __init__(self, store: Optional[_DataStore] = None) -> None:");
A("        self._store = store or _store");
B();
A("    # -- Public API --------------------------------------------------------");
B();
A("    def create_homework(");
A("        self,");
A("        teacher_id: str,");
A("        class_id: str,");
A("        topics: List[str],");
A("        question_count: int,");
A("        due_date: datetime,");
A("        title: str,");
A("    ) -> Homework:");
A("        " + Q3);
A("        Yeni odev olusturur ve sinifa atar.");
A("");
A("        Args:");
A("            teacher_id: Ogretmen kimligi.");
A("            class_id: Sinif kimligi.");
A('            topics: Konu listesi (or. ["Kesirler", "Ondalik Sayilar"]).');
A("            question_count: Sorulacak soru adedi.");
A("            due_date: Son teslim tarihi.");
A("            title: Odev basligi.");
A("");
A("        Returns:");
A("            Olusturulan Homework nesnesi.");
A("");
A("        Raises:");
A("            ValueError: Gecersiz parametreler verildiginde.");
A("        " + Q3);
A('        if question_count <= 0:');
A('            raise ValueError("Soru sayisi pozitif olmalidir.")');
A("        if not topics:");
A('            raise ValueError("En az bir konu belirtilmelidir.")');
A("        if due_date <= datetime.utcnow():");
A('            raise ValueError("Son teslim tarihi gelecekte olmalidir.")');
B();
A("        homework_id = str(uuid.uuid4())");
A("        questions = self._store.generate_questions_for_topics(topics, question_count)");
A("        students = self._store.get_class_students(class_id)");
B();
A("        homework = Homework(");
A("            homework_id=homework_id,");
A("            teacher_id=teacher_id,");
A("            class_id=class_id,");
A("            title=title,");
A("            topics=topics,");
A("            question_count=question_count,");
A("            questions=questions,");
A("            due_date=due_date,");
A("            created_at=datetime.utcnow(),");
A("            status=HomeworkStatus.ASSIGNED,");
A("            toplam_ogrenci=len(students),");
A("        )");
B();
A("        self._store.homeworks[homework_id] = homework");
A("        return homework");
B();
A("    def get_homework(self, homework_id: str) -> Homework:");
A("        " + Q3 + "Odev detaylarini getirir." + Q3);
A("        if homework_id not in self._store.homeworks:");
A('            raise KeyError(f"Odev bulunamadi: {homework_id}")');
A("        homework = self._store.homeworks[homework_id]");
A("        self._refresh_homework_status(homework)");
A("        return homework");
B();
A("    def submit_homework(");
A("        self,");
A("        homework_id: str,");
A("        student_id: str,");
A("        answers: List[Dict[str, Any]],");
A("    ) -> HomeworkSubmission:");
A("        " + Q3);
A("        Ogrenci odev teslimi yapar.");
A("");
A("        Args:");
A("            homework_id: Odev kimligi.");
A("            student_id: Ogrenci kimligi.");
A('            answers: Cevap listesi, her biri {"question_id": str, "answer": str} biciminde.');
A("");
A("        Returns:");
A("            HomeworkSubmission nesnesi.");
A("        " + Q3);
A("        homework = self.get_homework(homework_id)");
B();
A("        if homework.status == HomeworkStatus.CANCELLED:");
A('            raise ValueError("Bu odev iptal edilmistir.")');
A("        if datetime.utcnow() > homework.due_date:");
A('            raise ValueError("Odev teslim suresi gecmistir.")');
B();
A("        existing = self._find_submission(homework_id, student_id)");
A("        if existing is not None:");
A('            raise ValueError("Bu odev zaten teslim edilmis.")');
B();
A("        submission_id = str(uuid.uuid4())");
A("        submission = HomeworkSubmission(");
A("            submission_id=submission_id,");
A("            homework_id=homework_id,");
A("            student_id=student_id,");
A("            answers=answers,");
A("            submitted_at=datetime.utcnow(),");
A("        )");
B();
A("        self._store.submissions[submission_id] = submission");
A("        homework.teslim_sayisi += 1");
A("        if homework.status == HomeworkStatus.ASSIGNED:");
A("            homework.status = HomeworkStatus.IN_PROGRESS");
A("        return submission");
B();
A("    def grade_homework(self, homework_id: str) -> Dict[str, Any]:");
A("        " + Q3 + "Odeve ait tum teslimleri otomatik degerlendirir." + Q3);
A("        homework = self.get_homework(homework_id)");
A("        submissions = self._get_homework_submissions(homework_id)");
B();
A("        if not submissions:");
A("            return {");
A('                "homework_id": homework_id,');
A('                "graded_count": 0,');
A('                "sinif_ortalamasi": 0.0,');
A('                "en_yuksek_puan": 0.0,');
A('                "en_dusuk_puan": 0.0,');
A('                "submissions": [],');
A("            }");
B();
A("        scores: List[float] = []");
A("        for submission in submissions:");
A("            self._grade_single_submission(submission, homework)");
A("            if submission.score is not None:");
A("                scores.append(submission.score)");
B();
A("        avg_score = statistics.mean(scores) if scores else 0.0");
A("        homework.sinif_ortalamasi = round(avg_score, 2)");
A("        homework.status = HomeworkStatus.GRADED");
B();
A("        return {");
A('            "homework_id": homework_id,');
A('            "graded_count": len(submissions),');
A('            "sinif_ortalamasi": round(avg_score, 2),');
A('            "en_yuksek_puan": max(scores) if scores else 0.0,');
A('            "en_dusuk_puan": min(scores) if scores else 0.0,');
A('            "submissions": submissions,');
A("        }");

// Save progress
const b64 = Buffer.from(py, "utf8").toString("base64");
fs.writeFileSync(p.join("C:", "Users", "ahmet", "Desktop", ".github", "_part_hw.b64"), b64, "utf8");
console.log("HomeworkService part 1 saved, length:", py.length);
