const fs = require("fs");
const pp = require("path");
const target = pp.join("C:", "Users", "ahmet", "Desktop", ".github",
    "adaptive-math-learning", "backend", "services",
    "enhanced_parent_teacher_service.py");
const DQ = String.fromCharCode(34);
const SQ = String.fromCharCode(39);
const Q3 = DQ + DQ + DQ;
const JOIN_SEP = SQ + ", " + SQ;
const lines = [];
function L(s) { lines.push(s); }
function B() { lines.push(""); }

B(); B();
L("# ---------------------------------------------------------------------------");
L("# WeeklyReportService - Haftalik Raporlar");
L("# ---------------------------------------------------------------------------");
B();
L("class WeeklyReportService:");
L("    " + Q3);
L("    Haftalik ogrenme raporu olusturma ve e-posta hazirlama servisi.");
L("    Veliler cocuklarinin haftalik ilerlemesini takip edebilir.");
L("    " + Q3);
B();
L("    def __init__(self, store: Optional[_DataStore] = None) -> None:");
L("        self._store = store or _store");
B();
L("    def generate_weekly_report(self, child_id: str) -> WeeklyReport:");
L("        " + Q3 + "Son bir hafta icin kapsamli ilerleme raporu uretir." + Q3);
L("        now = datetime.utcnow()");
L("        week_start = now - timedelta(days=7)");
L("        week_end = now");
L("        activities = self._store.get_student_activity(child_id, since=week_start)");
L("        prev_week_start = week_start - timedelta(days=7)");
L("        prev_activities = self._store.get_student_activity(child_id, since=prev_week_start)");
L("        prev_activities = [a for a in prev_activities");
L("                           if a.get(" + DQ + "timestamp" + DQ + ", datetime.min) < week_start]");
B();
L("        toplam_soru = self._count_questions(activities)");
L("        dogru_sayisi = self._count_correct(activities)");
L("        dogru_orani = round((dogru_sayisi / toplam_soru) * 100, 2) if toplam_soru > 0 else 0.0");
L("        calisma_suresi = self._total_minutes(activities)");
L("        aktif_gunler = self._active_days(activities)");
L("        en_uzun_seri = self._longest_streak(activities)");
B();
L("        prev_soru = self._count_questions(prev_activities)");
L("        prev_dogru = self._count_correct(prev_activities)");
L("        prev_dogru_orani = round((prev_dogru / prev_soru) * 100, 2) if prev_soru > 0 else 0.0");
L("        prev_sure = self._total_minutes(prev_activities)");
B();
L("        soru_degisim = self._percentage_change(prev_soru, toplam_soru)");
L("        dogruluk_degisim = round(dogru_orani - prev_dogru_orani, 2)");
L("        sure_degisim = self._percentage_change(prev_sure, calisma_suresi)");
B();
L("        topic_stats = self._topic_breakdown(activities)");
L("        prev_topic_stats = self._topic_breakdown(prev_activities)");
L("        guclu = [t for t, s in topic_stats.items() if s >= 80]");
L("        zayif = [t for t, s in topic_stats.items() if s < 50]");
L("        gelisen = [t for t in topic_stats if t in prev_topic_stats and topic_stats[t] - prev_topic_stats[t] >= 10]");
L("        gerileyen = [t for t in topic_stats if t in prev_topic_stats and prev_topic_stats[t] - topic_stats[t] >= 10]");
L("        oneriler = self._generate_suggestions(dogru_orani, toplam_soru, calisma_suresi, aktif_gunler, zayif)");
L("        oncelikli = zayif[:3] if zayif else []");
L("        goal_progress = self._get_goal_progress(child_id)");
B();
L("        report_id = str(uuid.uuid4())");
L("        report = WeeklyReport(report_id=report_id, child_id=child_id,");
L("            week_start=week_start, week_end=week_end, generated_at=now,");
L("            toplam_soru=toplam_soru, dogru_orani=dogru_orani,");
L("            calisma_suresi_dakika=calisma_suresi, aktif_gun_sayisi=aktif_gunler,");
L("            en_uzun_seri=en_uzun_seri, guclu_konular=guclu, zayif_konular=zayif,");
L("            gelisen_konular=gelisen, gerileyen_konular=gerileyen,");
L("            soru_degisim_yuzdesi=soru_degisim, dogruluk_degisim=dogruluk_degisim,");
L("            sure_degisim_yuzdesi=sure_degisim, oneriler=oneriler,");
L("            oncelikli_konular=oncelikli, goal_progress=goal_progress)");
L("        self._store.weekly_reports[report_id] = report");
L("        return report");
B();
L("    def send_email_report(self, parent_id: str, child_id: str) -> Dict[str, Any]:");
L("        " + Q3 + "E-posta gonderime hazir rapor verisi dondurur." + Q3);
L("        report = self.generate_weekly_report(child_id)");
L("        parent_email = self._store.parent_emails.get(parent_id, f" + DQ + "{parent_id}@example.com" + DQ + ")");
L("        child_name = self._store.get_student_name(child_id)");
L("        subject = f" + DQ + "Haftalik Matematik Raporu - {child_name}" + DQ);
L("        return {" + DQ + "to" + DQ + ": parent_email, " + DQ + "subject" + DQ + ": subject, " + DQ + "report" + DQ + ": report}");
B();
L("    def get_report_history(self, child_id: str, weeks: int = 12) -> List[Dict[str, Any]]:");
L("        " + Q3 + "Gecmis haftalik raporlarin ozetini dondurur." + Q3);
L("        cutoff = datetime.utcnow() - timedelta(weeks=weeks)");
L("        reports = [r for r in self._store.weekly_reports.values()");
L("                   if r.child_id == child_id and r.generated_at >= cutoff]");
L("        reports.sort(key=lambda r: r.week_start)");
L("        return [{" + DQ + "report_id" + DQ + ": r.report_id,");
L("                 " + DQ + "week_start" + DQ + ": r.week_start.isoformat(),");
L("                 " + DQ + "week_end" + DQ + ": r.week_end.isoformat(),");
L("                 " + DQ + "toplam_soru" + DQ + ": r.toplam_soru,");
L("                 " + DQ + "dogru_orani" + DQ + ": r.dogru_orani,");
L("                 " + DQ + "calisma_suresi_dakika" + DQ + ": r.calisma_suresi_dakika,");
L("                 " + DQ + "aktif_gun_sayisi" + DQ + ": r.aktif_gun_sayisi,");
L("                 " + DQ + "guclu_konular" + DQ + ": r.guclu_konular,");
L("                 " + DQ + "zayif_konular" + DQ + ": r.zayif_konular} for r in reports]");

fs.appendFileSync(target, lines.join("\n") + "\n", "utf8");
console.log("WeeklyReport part a appended:", lines.length, "lines");
