const fs = require("fs");
const pp = require("path");
const target = pp.join("C:", "Users", "ahmet", "Desktop", ".github",
    "adaptive-math-learning", "backend", "services",
    "enhanced_parent_teacher_service.py");
const DQ = String.fromCharCode(34);
const SQ = String.fromCharCode(39);
const Q3 = DQ + DQ + DQ;
const COMMA_JOIN = SQ + ", " + SQ;
const lines = [];
function L(s) { lines.push(s); }
function B() { lines.push(""); }

B();
L("    # -- Private helpers ---------------------------------------------------");
B();
L("    @staticmethod");
L("    def _count_questions(activities: List[Dict[str, Any]]) -> int:");
L("        return sum(a.get(" + DQ + "questions_answered" + DQ + ", 0) for a in activities)");
B();
L("    @staticmethod");
L("    def _count_correct(activities: List[Dict[str, Any]]) -> int:");
L("        return sum(a.get(" + DQ + "correct_answers" + DQ + ", 0) for a in activities)");
B();
L("    @staticmethod");
L("    def _total_minutes(activities: List[Dict[str, Any]]) -> int:");
L("        return sum(a.get(" + DQ + "duration_minutes" + DQ + ", 0) for a in activities)");
B();
L("    @staticmethod");
L("    def _active_days(activities: List[Dict[str, Any]]) -> int:");
L("        days = set()");
L("        for a in activities:");
L("            ts = a.get(" + DQ + "timestamp" + DQ + ")");
L("            if isinstance(ts, datetime):");
L("                days.add(ts.date())");
L("        return len(days)");
B();
L("    @staticmethod");
L("    def _longest_streak(activities: List[Dict[str, Any]]) -> int:");
L("        max_streak = 0");
L("        current = 0");
L("        for a in activities:");
L("            for r in a.get(" + DQ + "results" + DQ + ", []):");
L("                if r.get(" + DQ + "correct" + DQ + "):");
L("                    current += 1");
L("                    max_streak = max(max_streak, current)");
L("                else:");
L("                    current = 0");
L("        return max_streak");
B();
L("    @staticmethod");
L("    def _topic_breakdown(activities: List[Dict[str, Any]]) -> Dict[str, float]:");
L("        topic_correct: Dict[str, int] = {}");
L("        topic_total: Dict[str, int] = {}");
L("        for a in activities:");
L("            topic = a.get(" + DQ + "topic" + DQ + ", " + DQ + "Genel" + DQ + ")");
L("            answered = a.get(" + DQ + "questions_answered" + DQ + ", 0)");
L("            correct = a.get(" + DQ + "correct_answers" + DQ + ", 0)");
L("            topic_total[topic] = topic_total.get(topic, 0) + answered");
L("            topic_correct[topic] = topic_correct.get(topic, 0) + correct");
L("        return {t: round((topic_correct.get(t, 0) / total) * 100, 2) if total > 0 else 0.0");
L("                for t, total in topic_total.items()}");
B();
L("    @staticmethod");
L("    def _percentage_change(old: float, new: float) -> float:");
L("        if old == 0:");
L("            return 100.0 if new > 0 else 0.0");
L("        return round(((new - old) / old) * 100, 2)");
B();
L("    def _generate_suggestions(self, accuracy, total_q, minutes, active_days, weak_topics):");
L("        suggestions: List[str] = []");
L("        if active_days < 3:");
L("            suggestions.append(f" + DQ + "Bu hafta yalnizca {active_days} gun calisildi." + DQ + ")");
L("        if accuracy < 60:");
L("            suggestions.append(f" + DQ + "Dogruluk orani dusuk (%{accuracy})." + DQ + ")");
L("        if total_q < 20:");
L("            suggestions.append(f" + DQ + "Bu hafta yalnizca {total_q} soru cozuldu." + DQ + ")");
L("        if minutes < 30:");
L("            suggestions.append(f" + DQ + "Toplam calisma suresi {minutes} dakika." + DQ + ")");
L("        if weak_topics:");
L("            suggestions.append(f" + DQ + "Zayif konular: {" + COMMA_JOIN + ".join(weak_topics)}." + DQ + ")");
L("        if not suggestions:");
L("            suggestions.append(" + DQ + "Harika bir hafta gecirildi! Ayni tempoda devam edin." + DQ + ")");
L("        return suggestions");
B();
L("    def _get_goal_progress(self, child_id: str) -> List[Dict[str, Any]]:");
L("        goals = [g for g in self._store.learning_goals.values()");
L("                 if g.child_id == child_id and g.is_active]");
L("        return [{" + DQ + "goal_id" + DQ + ": g.goal_id, " + DQ + "goal_type" + DQ + ": g.goal_type.value,");
L("                 " + DQ + "target_value" + DQ + ": g.target_value, " + DQ + "current_value" + DQ + ": g.current_value,");
L("                 " + DQ + "progress_percentage" + DQ + ": g.progress_percentage,");
L("                 " + DQ + "deadline" + DQ + ": g.deadline.isoformat() if g.deadline else None}");
L("                for g in goals]");

fs.appendFileSync(target, lines.join("\n") + "\n", "utf8");
console.log("WeeklyReport helpers appended:", lines.length, "lines");
