const fs = require("fs");
const pp = require("path");
const target = pp.join("C:", "Users", "ahmet", "Desktop", ".github",
    "adaptive-math-learning", "backend", "services",
    "enhanced_parent_teacher_service.py");
const DQ = String.fromCharCode(34);
const SQ = String.fromCharCode(39);
const Q3 = DQ + DQ + DQ;
const lines = [];
function L(s) { lines.push(s); }
function B() { lines.push(""); }

B();
L("    def get_student_homework_list(self, student_id: str) -> Dict[str, List[Dict[str, Any]]]:");
L("        " + Q3 + "Ogrencinin bekleyen ve tamamlanan odevlerini listeler." + Q3);
L("        bekleyen: List[Dict[str, Any]] = []");
L("        tamamlanan: List[Dict[str, Any]] = []");
L("        suresi_gecmis: List[Dict[str, Any]] = []");
L("        for hw in self._store.homeworks.values():");
L("            class_students = self._store.get_class_students(hw.class_id)");
L("            if student_id not in class_students:");
L("                continue");
L("            submission = self._find_submission(hw.homework_id, student_id)");
L("            hw_info = {" + DQ + "homework_id" + DQ + ": hw.homework_id, " + DQ + "title" + DQ + ": hw.title,");
L("                " + DQ + "topics" + DQ + ": hw.topics, " + DQ + "question_count" + DQ + ": hw.question_count,");
L("                " + DQ + "due_date" + DQ + ": hw.due_date.isoformat(), " + DQ + "status" + DQ + ": hw.status.value}");
L("            if submission is not None:");
L("                hw_info[" + DQ + "score" + DQ + "] = submission.score");
L("                hw_info[" + DQ + "submitted_at" + DQ + "] = submission.submitted_at.isoformat()");
L("                tamamlanan.append(hw_info)");
L("            elif datetime.utcnow() > hw.due_date:");
L("                suresi_gecmis.append(hw_info)");
L("            else:");
L("                kalan = hw.due_date - datetime.utcnow()");
L("                hw_info[" + DQ + "kalan_sure_saat" + DQ + "] = round(kalan.total_seconds() / 3600, 1)");
L("                bekleyen.append(hw_info)");
L("        return {" + DQ + "bekleyen" + DQ + ": bekleyen, " + DQ + "tamamlanan" + DQ + ": tamamlanan, " + DQ + "suresi_gecmis" + DQ + ": suresi_gecmis}");
B();
L("    # -- Private helpers ---------------------------------------------------");
B();
L("    def _refresh_homework_status(self, homework: Homework) -> None:");
L("        if (homework.status in (HomeworkStatus.ASSIGNED, HomeworkStatus.IN_PROGRESS)");
L("                and datetime.utcnow() > homework.due_date):");
L("            homework.status = HomeworkStatus.OVERDUE");
B();
L("    def _find_submission(self, homework_id: str, student_id: str) -> Optional[HomeworkSubmission]:");
L("        for sub in self._store.submissions.values():");
L("            if sub.homework_id == homework_id and sub.student_id == student_id:");
L("                return sub");
L("        return None");
B();
L("    def _get_homework_submissions(self, homework_id: str) -> List[HomeworkSubmission]:");
L("        return [s for s in self._store.submissions.values() if s.homework_id == homework_id]");
B();
L("    def _grade_single_submission(self, submission: HomeworkSubmission, homework: Homework) -> None:");
L("        " + Q3 + "Tek bir teslimi degerlendirir." + Q3);
L("        answer_map = {a[" + DQ + "question_id" + DQ + "]: a.get(" + DQ + "answer" + DQ + ") for a in submission.answers}");
L("        dogru, yanlis, bos = 0, 0, 0");
L("        topic_correct: Dict[str, int] = {}");
L("        topic_total: Dict[str, int] = {}");
L("        for q in homework.questions:");
L("            qid = q[" + DQ + "question_id" + DQ + "]");
L("            topic = q[" + DQ + "topic" + DQ + "]");
L("            topic_total[topic] = topic_total.get(topic, 0) + 1");
L("            student_answer = answer_map.get(qid)");
L("            if student_answer is None or student_answer == " + DQ + DQ + ":");
L("                bos += 1");
L("            elif student_answer == q[" + DQ + "dogru_cevap" + DQ + "]:");
L("                dogru += 1");
L("                topic_correct[topic] = topic_correct.get(topic, 0) + 1");
L("            else:");
L("                yanlis += 1");
L("        total = len(homework.questions)");
L("        score = round((dogru / total) * 100, 2) if total > 0 else 0.0");
L("        topic_scores: Dict[str, float] = {}");
L("        for topic, total_q in topic_total.items():");
L("            correct_q = topic_correct.get(topic, 0)");
L("            topic_scores[topic] = round((correct_q / total_q) * 100, 2) if total_q > 0 else 0.0");
L("        submission.score = score");
L("        submission.dogru_sayisi = dogru");
L("        submission.yanlis_sayisi = yanlis");
L("        submission.bos_sayisi = bos");
L("        submission.topic_scores = topic_scores");
L("        submission.graded_at = datetime.utcnow()");
L("        submission.feedback = self._generate_feedback(score, topic_scores)");
B();
L("    @staticmethod");
L("    def _generate_feedback(score: float, topic_scores: Dict[str, float]) -> str:");
L("        " + Q3 + "Puana gore otomatik geri bildirim uretir." + Q3);
L("        if score >= 90:");
L("            feedback = " + DQ + "Harika bir performans! Tebrikler." + DQ);
L("        elif score >= 70:");
L("            feedback = " + DQ + "Iyi bir calisma, biraz daha pratik yaparak daha da iyilesebilirsin." + DQ);
L("        elif score >= 50:");
L("            feedback = " + DQ + "Ortalama bir sonuc. Zayif konularina odaklanmani oneririm." + DQ);
L("        else:");
L("            feedback = " + DQ + "Bu konularda daha fazla calisman gerekiyor." + DQ);
L("        weak_topics = [t for t, s in topic_scores.items() if s < 50]");
L("        if weak_topics:");
L("            feedback += f" + DQ + " Ozellikle su konulara calis: {" + SQ + ", " + SQ + ".join(weak_topics)}." + DQ);
L("        return feedback");

fs.appendFileSync(target, lines.join("\n") + "\n", "utf8");
console.log("HW part c appended:", lines.length, "lines");
